spring:
  application:
    name: customers
  rabbitmq:
    host: @jbazann.amqp.host@
    port: @jbazann.amqp.port@
    username: @jbazann.amqp.username@
    password: @jbazann.amqp.password@
    virtual-host: @jbazann.amqp.username@
    ssl:
      verify-hostname: false
      enabled: true
  datasource:
    customer:
      jdbc-url: jdbc:mysql://mysql:12012/customer
      username: customers
      password: customers
      driver-class-name: com.mysql.cj.jdbc.Driver
    site:
      jdbc-url: jdbc:mysql://mysql:12012/site
      username: customers
      password: customers
      driver-class-name: com.mysql.cj.jdbc.Driver
    user:
      jdbc-url: jdbc:mysql://mysql:12012/user
      username: customers
      password: customers
      driver-class-name: com.mysql.cj.jdbc.Driver

server:
  port: @jbazann.kube.main-port@

eureka:
  client:
    serviceUrl:
      defaultZone: @jbazann.eureka.defaultZone@
    fetch-registry: false

management:
  server:
    port: @jbazann.kube.management-port@
  endpoints:
    web:
      exposure:
        include: httpexchanges,health,prometheus

jbazann:
  timeout:
    standard: @jbazann.timeout.standard@
  rabbit:
    exchanges:
      event: @jbazann.rabbit.exchanges.event@
    queues:
      event: @jbazann.rabbit.queues.customers.event@
    routing: # [escape].operation.queue.[source].[target]
      event: @jbazann.rabbit.routing.customers.event@