spring:
  application:
    name: customers
  rabbitmq:
    host: amqp-0
    port: 5671
    username: @jbazann.amqp.username@
    password: @jbazann.amqp.password@
    virtual-host: @jbazann.amqp.username@
    ssl:
      verify-hostname: false
      enabled: true
  datasource:
    customer:
      jdbc-url: jdbc:mysql://mysql:12012/customer
      username: customers
      password: customers
      jpa:
        hibernate:
          dialect: org.hibernate.dialect.MySQLDialect
    site:
      jdbc-url: jdbc:mysql://mysql:12012/site
      username: customers
      password: customers
      jpa:
        hibernate:
          dialect: org.hibernate.dialect.MySQLDialect
    user:
      jdbc-url: jdbc:mysql://mysql:12012/user
      username: customers
      password: customers

server:
  port: @jbazann.kube.main-port@

eureka:
  client:
    serviceUrl:
      defaultZone: http://eureka:@jbazann.kube.main-port@/eureka/
    fetch-registry: false

management:
  server:
    port: @jbazann.kube.management-port@
  endpoints:
    web:
      exposure:
        include: httpexchanges,health

jbazann:
  rabbit:
    exchanges:
      customers: @jbazann.rabbit.exchanges.customers@
      orders: @jbazann.rabbit.exchanges.orders@
      users: @jbazann.rabbit.exchanges.users@
    queues:
      saga: @jbazann.rabbit.queues.saga@
      operation: @jbazann.rabbit.queues.operation@