apiVersion: apps/v1
kind: Deployment
metadata:
  name: products
  namespace: products
spec:
  replicas: 1
  selector:
    matchLabels:
      app: products
  template:
    metadata:
      labels:
        app: products
    spec:
      containers:
        - name: app
          image: skwidl/products:latest
          ports:
            - name: app
              containerPort: 12012
            - name: probe
              containerPort: 12112
          livenessProbe:
            httpGet:
              path: /actuator/health
              port: 12112
              scheme: HTTP
            initialDelaySeconds: 5000
            timeoutSeconds: 15
          readinessProbe:
            httpGet:
              path: /actuator/health
              port: 12112
              scheme: HTTP
            initialDelaySeconds: 5000
            timeoutSeconds: 15
          securityContext:
            privileged: false