apiVersion: v1
kind: Service
metadata:
  name: postgresql
  namespace: products
spec:
  selector:
    app: postgresql
  ports:
    - protocol: TCP
      port: 12012
      targetPort: 12012
  type: ClusterIP
  