apiVersion: v1
kind: Service
metadata:
  name: products
  namespace: products
spec:
  type: ClusterIP
  clusterIP: None
  selector:
    app: products
  ports:
    - name: app
      port: 12012
      targetPort: 12012
    - name: probe
      port: 12112
      targetPort: 12112