apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: eureka
  namespace: eureka
  labels:
    app: eureka
spec:
  serviceName: eureka
  replicas: 2
  selector:
    matchLabels:
      app: eureka
  template:
    metadata:
      name: eureka
      labels:
        app: eureka
    spec:
      containers:
        - name: app
          image: skwidl/eureka:latest
          imagePullPolicy: IfNotPresent
          ports:
            - name: app
              containerPort: 12012
            - name: probe
              containerPort: 12112
          livenessProbe:
            httpGet:
              path: /actuator/health
              port: 12112
              scheme: HTTP
            initialDelaySeconds: 60
            timeoutSeconds: 15
            failureThreshold: 5
            periodSeconds: 20
          readinessProbe:
            httpGet:
              path: /actuator/health
              port: 12112
              scheme: HTTP
            initialDelaySeconds: 60
            timeoutSeconds: 15
            failureThreshold: 5
            periodSeconds: 20
          securityContext:
            privileged: false
      restartPolicy: Always
      