apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: graylog
  namespace: graylog
spec:
  serviceName: graylog
  replicas: 1
  selector:
    matchLabels:
      app: graylog
  template:
    metadata:
      labels:
        app: graylog
    spec:
      containers:
        - name: logs
          image: graylog/graylog:6.0.5-1
          ports:
            - name: app
              containerPort: 12012
              protocol: UDP
            - name: http
              containerPort: 80
              protocol: TCP
            - name: https
              containerPort: 443
              protocol: TCP
          env:
            - name: POD_NAME # graylog picks this up to set pod-0 as master node
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
          envFrom:
            - configMapRef:
                name: graylog-env
          securityContext:
            privileged: false
          volumeMounts:
            - mountPath: /usr/share/graylog/data/contentpacks/content-pack-2942753d-93b6-4875-9496-c7b0ae66ffed-1.json
              subPath: content-pack-2942753d-93b6-4875-9496-c7b0ae66ffed-1.json
              name: graylog-content-pack
      volumes:
        - name: graylog-content-pack
          configMap:
            name: graylog-content-pack