apiVersion: v1
kind: ConfigMap
metadata:
  name: graylog-content-pack
  namespace: graylog
data:
  content-pack-2942753d-93b6-4875-9496-c7b0ae66ffed-1.json: |
    {
      "v": 1,
      "id": "2942753d-93b6-4875-9496-c7b0ae66ffed",
      "rev": 1,
      "name": "main_udp_input",
      "summary": "why are you reading this",
      "description": "",
      "vendor": "jbazann.dev",
      "url": "",
      "parameters": [],
      "entities": [
        {
          "v": "1",
          "type": {
            "name": "input",
            "version": "1"
          },
          "id": "2fe53755-8b0d-4263-83bf-ff89fb90e542",
          "data": {
            "title": {
              "@type": "string",
              "@value": "main_udp"
            },
            "configuration": {
              "port": {
                "@type": "integer",
                "@value": 12012
              },
              "number_worker_threads": {
                "@type": "integer",
                "@value": 4
              },
              "charset_name": {
                "@type": "string",
                "@value": "UTF-8"
              },
              "bind_address": {
                "@type": "string",
                "@value": "0.0.0.0"
              }
            },
            "static_fields": {},
            "type": {
              "@type": "string",
              "@value": "org.graylog2.inputs.gelf.udp.GELFUDPInput"
            },
            "global": {
              "@type": "boolean",
              "@value": false
            },
            "extractors": []
          },
          "constraints": [
            {
              "type": "server-version",
              "version": ">=6.0.5+3ef5be7"
            }
          ]
        }
      ]
    }
