apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: graylog
  namespace: graylog
spec:
  serviceName: graylog
  replicas: 1
  selector:
    matchLabels:
      app: graylog
  template:
    metadata:
      labels:
        app: graylog
    spec:
      containers:
        - name: logs
          image: graylog/graylog:6.0.5-1
          ports:
            - name: app
              containerPort: 12012
            - name: http
              containerPort: 80
            - name: https
              containerPort: 443
          env:
            - name: POD_NAME # graylog picks this up to set pod-0 as master node
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
          envFrom:
            - configMapRef:
                name: graylog-env
          securityContext:
            privileged: false
          volumeMounts:
            - mountPath: /usr/share/graylog/data/contentpacks/content-pack-30b6afa7-fcd4-4c7b-b70b-b21b5cf33b7f-1.json
              subPath: content-pack-30b6afa7-fcd4-4c7b-b70b-b21b5cf33b7f-1.json
              name: graylog-content-pack
      volumes:
        - name: graylog-content-pack
          configMap:
            name: graylog-content-pack