apiVersion: v1
kind: Service
metadata:
  name: graylog
  namespace: graylog
spec:
  type: ClusterIP
  selector:
    app: graylog
  ports:
    - name: app
      port: 12012
      targetPort: 12012
      protocol: UDP
    - name: http
      port: 80
      targetPort: 80
      appProtocol: HTTP
    - name: https
      port: 443
      targetPort: 443
      appProtocol: HTTPS