apiVersion: v1
kind: Service
metadata:
  name: customers
spec:
  type: ExternalName
  externalName: customers.customers.svc.cluster.local # TODO do not use external name for this redirection
  ports:
    - port: 12112
      name: admin
      protocol: TCP