apiVersion: v1
kind: Service
metadata:
  name: grafana
spec:
  type: ExternalName
  externalName: grafana.metrics.svc.cluster.local # TODO do not use external name for this redirection
  ports:
    - port: 80
      name: http
      appProtocol: HTTP