apiVersion: v1
kind: Service
metadata:
  name: graylog
spec:
  type: ExternalName
  externalName: graylog.graylog.svc.cluster.local # TODO do not use external name for this redirection
  ports:
    - port: 12012
      name: app
      protocol: TCP