apiVersion: v1
kind: Service
metadata:
  name: graylog
spec:
  type: ExternalName
  externalName: graylog.graylog.svc.cluster.local # TODO do not use external name for this redirection
  ports:
    - port: 80
      name: http
      appProtocol: HTTP
    - port: 443
      name: https
      appProtocol: HTTPS