apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: haproxy
  annotations:
    haproxy.org/path-rewrite: |
      /ui/(.*) /\1
spec:
  ingressClassName: haproxy
  rules:
    - host: localhost
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: nodejs
                port:
                  name: app
    - host: skwidl.jbazann.dev
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: nodejs
                port:
                  name: app
    - host: api.skwidl.jbazann.dev
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: gateway
                port:
                  name: app
    - host: graylog.skwidl.jbazann.dev
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: graylog
                port:
                  name: http
    - host: grafana.skwidl.jbazann.dev
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: grafana
                port:
                  name: http
    - host: orders.skwidl.jbazann.dev
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: orders
                port:
                  name: admin
    - host: products.skwidl.jbazann.dev
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: products
                port:
                  name: admin
    - host: customers.skwidl.jbazann.dev
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: customers
                port:
                  name: admin