apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: haproxy
  annotations:
    haproxy.org/path-rewrite: |
      /ui/(.*) /\1
spec:
  ingressClassName: haproxy
  rules:
    - host: localhost
      http:
        paths:
          - path: /api/
            pathType: Prefix
            backend:
              service:
                name: gateway
                port:
                  name: app
          - path: /
            pathType: Prefix
            backend:
              service:
                name: nodejs
                port:
                  name: app
    - host: graylog.127.0.0.1.nip.io
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: graylog
                port:
                  name: http
    - host: grafana.127.0.0.1.nip.io
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: grafana
                port:
                  name: app