apiVersion: v1
kind: Service
metadata:
  name: orders
spec:
  type: ExternalName
  externalName: orders.orders.svc.cluster.local # TODO do not use external name for this redirection
  ports:
    - port: 12112
      name: admin
      protocol: TCP