apiVersion: v1
kind: Service
metadata:
  name: products
spec:
  type: ExternalName
  externalName: products.products.svc.cluster.local # TODO do not use external name for this redirection
  ports:
    - port: 12112
      name: admin
      protocol: TCP