apiVersion: v1
kind: Service
metadata:
  name: prometheus
spec:
  type: ExternalName
  externalName: prometheus.metrics.svc.cluster.local # TODO do not use external name for this redirection
  ports:
    - port: 12012
      name: app
      protocol: TCP