spring:
  application:
    name: orders
  config:
    import: routes.yml
  data:
    mongodb:
      username: orders
      password: orders
      uri: mongodb://mongodb:12012/orders
      uuid-representation: standard
  rabbitmq:
    host: @jbazann.amqp.host@
    port: @jbazann.amqp.port@
    username: @jbazann.amqp.username@
    password: @jbazann.amqp.password@
    virtual-host: @jbazann.amqp.username@
    ssl:
      verify-hostname: false
      enabled: true


server:
  port: @jbazann.kube.main-port@

eureka:
  client:
    serviceUrl:
      defaultZone: @jbazann.eureka.defaultZone@
    fetch-registry: false

management:
  server:
    port: @jbazann.kube.management-port@
  endpoints:
    web:
      exposure:
        include: httpexchanges,health,prometheus

jbazann:
  timeout:
    standard: @jbazann.timeout.standard@
  rabbit:
    exchanges:
      event: @jbazann.rabbit.exchanges.event@
    queues:
      coordination:
        event: @jbazann.rabbit.queues.coordination.event@
      event: @jbazann.rabbit.queues.orders.event@
    routing: # [escape].operation.queue.[source].[target]
      event: @jbazann.rabbit.routing.orders.event@