apiVersion: apps/v1
kind: Deployment
metadata:
  name: commons-artifact
  namespace: commons
spec:
  replicas: 1
  selector:
    matchLabels:
      app: commons-artifact
  template:
    metadata:
      labels:
        app: commons-artifact
    spec:
      containers:
        - name: app
          image: skwidl/commons-artifact:latest
          ports:
            - name: app
              containerPort: 12012
            - name: probe
              containerPort: 12112
          livenessProbe:
            httpGet:
              path: /actuator/health
              port: 12112
              scheme: HTTP
            initialDelaySeconds: 60
            timeoutSeconds: 15
            failureThreshold: 5
            periodSeconds: 20
          readinessProbe:
            httpGet:
              path: /actuator/health
              port: 12112
              scheme: HTTP
            initialDelaySeconds: 60
            timeoutSeconds: 15
            failureThreshold: 5
            periodSeconds: 20
          securityContext:
            privileged: false