apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: mongodb
  namespace: orders
  labels:
    app: mongodb
spec:
  serviceName: mongodb
  replicas: 1
  selector:
    matchLabels:
      app: mongodb
  template:
    metadata:
      name: mongodb
      labels:
        app: mongodb
    spec:
      containers:
        - name: db
          image: mongodb/mongodb-community-server:7.0.9-ubuntu2204
          imagePullPolicy: IfNotPresent
          args:
            - mongod
            - --config
            - /etc/mongod.conf
          ports:
            - name: app
              containerPort: 12012
          volumeMounts:
            - mountPath: /etc/mongod.conf
              subPath: mongod.conf
              name: mongodb-cfg
      restartPolicy: Always
      volumes:
        - name: mongodb-cfg
          configMap:
            name: mongodb-cfg