spring:
  profiles:
    active: @spring-profile@
  application:
    name: products
  rabbitmq:
    host: @jbazann.amqp.host@
    port: @jbazann.amqp.port@
    username: @jbazann.amqp.username@
    password: @jbazann.amqp.password@
    virtual-host: @jbazann.amqp.username@
    ssl:
      enabled: true
      verify-hostname: false
  datasource:
    product:
      jdbc-url: jdbc:postgresql://postgresql:12012/product
      username: product
      password: product
      driver-class-name: org.postgresql.Driver
    category:
      jdbc-url: jdbc:postgresql://postgresql:12012/category
      username: category
      password: category
      driver-class-name: org.postgresql.Driver

server:
  port: @jbazann.kube.main-port@

eureka:
  instance:
    hostname: products.products
    metadata-map:
      collections: "products,categories"
  client:
    serviceUrl:
      defaultZone: @jbazann.eureka.defaultZone@
    fetch-registry: false

management:
  server:
    port: @jbazann.kube.management-port@
  endpoints:
    web:
      exposure:
        include: httpexchanges,health,prometheus

jbazann:
  timeout:
    standard: @jbazann.timeout.standard@
  rabbit:
    exchanges:
      event: @jbazann.rabbit.exchanges.event@
    queues:
      event: @jbazann.rabbit.queues.products.event@
    routing: # [escape].operation.queue.[source].[target]
      event: @jbazann.rabbit.routing.products.event@