spring:
  application:
    name: products
  rabbitmq:
    host: @jbazann.amqp.host@
    port: @jbazann.amqp.port@
    username: @jbazann.amqp.username@
    password: @jbazann.amqp.password@
    virtual-host: @jbazann.amqp.username@
    ssl:
      enabled: true
      verify-hostname: false

server:
  port: @jbazann.kube.main-port@

eureka:
  client:
    serviceUrl:
      defaultZone: @jbazann.eureka.defaultZone@
    fetch-registry: false

management:
  server:
    port: @jbazann.kube.management-port@
  endpoints:
    web:
      exposure:
        include: httpexchanges,health