apiVersion: v1
kind: Service
metadata:
  name: shared-storage
  namespace: shared
spec:
  type: ClusterIP
  clusterIP: None
  selector:
    app: shared-storage
  ports:
    - name: app
      port: 12012
      targetPort: 12012