spring:
  application:
    name: eureka
#  cloud:
#    refresh:
#      enabled: false

server:
  port: @jbazann.kube.main-port@

eureka:
  instance:
    hostname: eureka.eureka
    metadata-map:
      region: santa-fe-1
  client:
    region: santa-fe-1
    serviceUrl:
      defaultZone: http://eureka-0.eureka:@jbazann.kube.main-port@/eureka/,http://eureka-1.eureka:@jbazann.kube.main-port@/eureka/

management:
  server:
    port: @jbazann.kube.management-port@
  endpoints:
    web:
      exposure:
        include: httpexchanges,health,prometheus