apiVersion: v1
kind: ConfigMap
metadata:
  name: prometheus-cfg
  namespace: metrics
data:
  prometheus.yml: |
    global:
      scrape_interval: 15s
    scrape_configs:
      - job_name: self
        static_configs:
          - targets: [localhost:12012]
      - job_name: eureka
        metrics_path: '/actuator/prometheus'
        eureka_sd_configs:
          - server: http://eureka.eureka:12012/eureka
        relabel_configs:
          - source_labels: [__meta_eureka_app_instance_ip_addr]
            target_label: __address__
            replacement: ${1}:12112